spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fmall?serverTimezone=America/New_York
    username: root
    password: 123456
  # session timeout (min)
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    host: localhost
  server:
    port: 8080
    servlet:
      context-path: /api
      session:
        cookie:
          domain: localhost
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: logs
    redis:
      database: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0